export const fcfe_fcff_headingObj = {
  particulars: 'Particulars',
  pat: 'PAT',
  depAndAmortisation: 'Depn and Amortisation',
  onCashItems: 'Other Non Cash items',
  nca: 'Change in NCA',
  defferedTaxAssets: 'Add/Less: Deferred Tax Assets(Net)',
  netCashFlow: 'Net Cash Flow',
  fixedAssets: 'Change in fixed assets',
  fcff: 'FCFF',
  discountingPeriod: 'Discounting Period (Mid Year)',
  discountingFactor: 'Discounting Factor @WACCAT',
  presentFCFF: 'Present Value of FCFF',
  sumOfCashFlows: 'Sum of Cash Flows',
  debtOnDate: 'Less: Debt as on Date',
  cashEquivalents: 'Add: Cash & Cash Equivalents',
  surplusAssets: 'Add: Surplus Assets/Investments',
  otherAdj: 'Add/Less: Other Adjustments(if any)',
  equityValue: 'Equity Value',
  noOfShares: 'No. of Shares',
  valuePerShare: 'Value per Share',
};
export const relative_valuation_headingObj = {
  pbRatioLabel: 'P/B Ratio',
  netWorth: 'Net Worth of Company',
  pbShares: 'Number of Shares',
  bookValue: 'Book Value per Share',
  pbRatio: 'P/B Ratio of Industry',
  pbMarketPrice: 'Market Price',
  peRatioLabel:"P/E Ratio",
  peRatio:"P/E Ratio of Industry",
  eps:"EPS",
  peMarketPrice: 'Market Price',
  ebitdaLabel:"EV/EBITDA",
  ebitda:"EBITDA",
  ev:"EV/EBITDA",
  enterprise:"Enterprise Value",
  debt:"Less : Value of Debt",
  ebitdaEquity:"Value of Equity",
  ebitdaShares:"Number of share",
  ebitdaMarketPrice:"Market Price",
  salesLabel:"Price to Sales",
  sales:"Sales of company (INR)",
  salesRatio:"P/S Ratio",
  salesEquity:"Value of Equity",
  salesShare:"Number of share",
  salesMarketPrice:"Market Price",
  avgPricePerShare:"Average Price per Share",
  average:"Average",
  loc:"Less: Illiquidity Discount/size/lack of control",
  finalPrice:"Final Price",
  tentativeIssuePrice:"Tentative Issue Price (Average of above)",
};
export const footerInfo = {
  address:
    '(Unit No. 8, 2nd Floor, Senior Estate, 7/C Parsi Panchayat Road, Andheri (East), Mumbai – 400069)',
  email: 'Valuation@ifinworth.com',
};
