// export const fcfe_fcff_headingObj = {
//   particulars: 'Particulars',
//   pat: 'PAT',
//   // addInterestAdjTaxes:'Add: Interest adjusted Taxes',
//   depAndAmortisation: 'Depn and Amortisation',
//   onCashItems: 'Other Non Cash items',
//   nca: 'Change in NCA',
//   changeInBorrowings: 'Chg in Borrowings',
//   defferedTaxAssets: 'Add/Less: Deferred Tax Assets(Net)',
//   netCashFlow: 'Net Cash Flow',
//   fixedAssets: 'Change in fixed assets',
//   fcff: 'FCFF',
//   discountingPeriod: 'Discounting Period',
//   discountingFactor: 'Discounting Factor',
//   presentFCFF: 'Present Value of FCFF',
//   sumOfCashFlows: 'Sum of Cash Flows',
//   // debtOnDate: 'Less: Debt as on Date',
//   cashEquivalents: 'Add: Cash & Cash Equivalents',
//   surplusAssets: 'Add: Surplus Assets/Investments',
//   otherAdj: 'Add/Less: Other Adjustments(if any)',
//   equityValue: 'Equity Value',
//   noOfShares: 'No. of Shares',
//   valuePerShare: 'Value per Share',
// };

export const fcfe_headingObj = {
  particulars: 'Particulars',
  pat: 'PAT',
  depAndAmortisation: 'Depn and Amortisation',
  onCashItems: 'Other Non Cash items',
  nca: 'Change in NCA',
  changeInBorrowings: 'Change in Borrowings',
  defferedTaxAssets: 'Add/Less: Deferred Tax Assets(Net)',
  netCashFlow: 'Net Cash Flow',
  fixedAssets: 'Change in fixed assets',
  fcff: 'FCFE',
  discountingPeriod: 'Discounting Period',
  discountingFactor: 'Discounting Factor',
  presentFCFF: 'Present Value of FCFE',
  sumOfCashFlows: 'Sum of Cash Flows',
  cashEquivalents: 'Add: Cash & Cash Equivalents',
  surplusAssets: 'Add: Surplus Assets/Investments',
  otherAdj: 'Add/Less: Other Adjustments(if any)',
  equityValue: 'Equity Value',
  noOfShares: 'No. of Shares',
  valuePerShare: 'Value per Share',
};

export const fcff_headingObj = {
  particulars: 'Particulars',
  pat: 'PAT',
  addInterestAdjTaxes:'Add: Interest adjusted Taxes',
  depAndAmortisation: 'Depn and Amortisation',
  onCashItems: 'Other Non Cash items',
  nca: 'Change in NCA',
  defferedTaxAssets: 'Add/Less: Deferred Tax Assets(Net)',
  netCashFlow: 'Net Cash Flow',
  fixedAssets: 'Change in fixed assets',
  fcff: 'FCFF',
  discountingPeriod: 'Discounting Period',
  discountingFactor: 'Discounting Factor',
  presentFCFF: 'Present Value of FCFF',
  sumOfCashFlows: 'Sum of Cash Flows',
  debtOnDate: 'Less: Debt as on Date',
  cashEquivalents: 'Add: Cash & Cash Equivalents',
  surplusAssets: 'Add: Surplus Assets/Investments',
  otherAdj: 'Add/Less: Other Adjustments(if any)',
  equityValue: 'Equity Value',
  noOfShares: 'No. of Shares',
  valuePerShare: 'Value per Share',
};
export const relative_valuation_headingObj = {
  pbRatioLabel: 'P/B Ratio',
  netWorth: 'Net Worth of Company',
  pbRatio: 'P/B Ratio of Industry',
  // pbRatioIndustry: 'P/B Ratio of Industry',
  pbShares: 'Number of Shares',
  fairValueEq: 'Fair Value of Equity',
  bookValue: 'Book Value per Share',
  pbMarketPrice: 'Market Price',
  
  peRatioLabel:"P/E Ratio",
  pat:"Profit after Taxes",
  peRatio:"P/E Ratio of Industry",
  peMarketPrice: 'Market Price',
  eps:"EPS",

  ebitdaLabel:"EV/EBITDA",
  ebitda:"EBITDA",
  ev:"EV/EBITDA",
  enterprise:"Enterprise Value",
  debt:"Less : Value of Debt",
  ebitdaEquity:"Value of Equity",
  ebitdaShares:"Number of shares",
  ebitdaMarketPrice:"Market Price",

  salesLabel:"Price to Sales",
  sales:"Sales of company (INR)",
  salesRatio:"P/S Ratio",
  salesEquity:"Value of Equity",

  salesShares:"Number of shares",
  salesMarketPrice:"Market Price",
  
  avgPricePerShare:"Average Price of Equity",
  average:"Average",
  loc:"Less: Illiquidity",
  noOfShares:"No. of Shares",
  finalPrice:"Fair Value per Share",
  tentativeIssuePrice:"Tentative Issue Price (Average of above)",
};
export const footerInfo = {
  address:
    '(Unit No. 8, 2nd Floor, Senior Estate, 7/C Parsi Panchayat Road, Andheri (East), Mumbai – 400069)',
  email: 'Valuation@ifinworth.com',
};
