//Years Columns List.
export const columnsList=['B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'];

export const sheet1_PLObj={

    incomeFromOperationRow:"7",
    otherOperatingIncome:"8",
    costofMaterialConsumedRow:"13",
    purchaseOfStockInTrade:"14",
    changeInInventoryRow:"15",
    employeeBenefitExpenses:"16",
    powerAndFuel:"17",
    labourCharges:"18",
    sellingAndAdministration:"19",
    sellingOver2:"20",
    sellingOver3:"21",
    sellingOver4:"22",
    ebitdaRow:"25",
    depAndAmortisationRow:"26",
    financeCostsRow:"28",
    otherIncomeRow:"29",
    exceptionalItemsRow:"31",
    extraordinaryItemsRow:"33",
    currentTaxExpense:"36",
    matCredit:"37",
    currentTaxExpensePrior:"38",
    netCurrentTaxExpense:"39",
    deferredTax:"40",
    patRow:"42",
    profitLossDiscontinuingOpsNetTax:"52",
    profitLossOfYear:"54",
    earningPerShareRow:"58",

    // =+B36+B37+B38+B39+B40
}

export const sheet2_BSObj={
    shareholderFundsRow:"6",
    equityShareCapitalRow:"7",
    preferenceShareCapitalRow:"8",
    otherEquityRow:"9",
    sharePremiumRow:"10",
    reserveAndSurplusRow:"11",
    revaluationReserveRow:"12",
    capitalReserveRow:"13",
    capitalRedemptionReserveRow:"14",
    debentureRedemptionReserveRow:"15",
    shareBasedPaymentReserveRow:"16",
    definedBenefitObligationReserveRow:"17",
    otherComprehensiveIncomeRow:"18",
    nonControllingInterestRow:"19",
    shareWarrantsRow:"21",
    shareApplicationRow:"22",
    deferredTaxLiabilityRow:"25",
    otherUnsecuredLoansRow:"26",
    longTermBorrowingsRow:"27",
    liabilityComponentofCCDRow:"28",
    longTermProvisionRow:"29",
    deferredGovtGrantRow:"31",
    tradePayablesRow:"34",
    employeePayablesRow:"35",
    shortTermBorrowingsRow:"36",
    lcPayablesRow:"37",
    otherCurrentLiabilitiesRow:"38",
    shortTermProvisionsRow:"39",
    interCoRow:"40",
    totalRow:"41",
    fixedAssetsRow:"46",
    netFixedAssetsRow:"47",

    tangibleAssetsRow:"48",
    intangibleAssetsRow:"49",
    capitalWorkInProgressRow:"50",
    preOperativeExpensesRow:"51",
    capitalAdvancesRow:"52",
    capitalLiabilitiesRow:"53",

    nonCurrentInvestmentRow:"56",
    otherNonCurrentAssetsRow:"58",
    deferredTaxAssetsRow:"59",
    cashEquivalentsRow:"62",
    bankBalancesRow:"63",
    tradeReceivablesRow:"64",
    unbilledRevenuesRow:"65",
    inventoriesRow:"66",
    advancesRow:"67",
    shortTermInvestmentsRow:"68",
    otherCurrentAssetsRow:"69"    

}

export const sheet3_assWCObj={
    otherOperatingAssetsRow : "10",
    totalOperatingAssetsRow : "11",
    otherOperatingLiabilitiesRow : "20",
    totalOperatingLiabilitiesRow : "21",
    netOperatingAssets : "23",
    changeInNca : "24",
}

export const sheet4_ruleElevenUaObj={
    immovablePropertyRow : "5",
    jewelleryRow : "6", 
    artisticWorkRow : "7",
    sharesAndSecuritiesRow : "8",
    otherTangibleAssets : "9",
    nonCurrentInvestmenInSharesAndSecuritesRow : "13",
    advanceTaxRow : "18",
    incomeTaxRefundRow : "19",
    defferedTaxRow : "20",
    currentInvestmentSharesAndSecuritesRow : "26",
    advanceTaxPaidRow : "36",
    preliminaryExpenseRow : "37",
    preOperativeTaxRow : "38",
    otherMiscllneousExpenseRow : "39",
    totalAssetsRow : "41",
    shareCapitalRow : "45",
    reserveAndSurplusRow : "46",
    paymentDividendsRow : "47",
    provisionForTaxationRow : "54",
    totalLiabilitiesRow: "69"
}